language: node_js
node_js:
  - 15.4.0

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed pre-test"

# Scripts to be rrun such as test
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-reverse-proxy .
  - docker tag simple-reverse-proxy theresmith/reverse_proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push theresmith/reverse_proxy:latest